### ISSUE TITLE
Remote Connection no Longer Working

### ISSUE THREAD

**Issue by asasin114** [ryanblenis/MeshCentral-WorkFromHome#3]
Hey @ryanblenis:

I'm on Mesh 0.5.1-q and work from home 0.0.5 and just had a client report that Work from Home has stopped working for them. When I go and test with my machine I notice that I can start the connection but RDP sits trying to "configure remote session" until it times out. Seems like a routing issue through Mesh Central. This is just with 0.5.1-q as I was having no issues with 0.5.1-m which was the last version I was on. I'm running Mesh on Windows Server 2019 if that helps anything.

**Comment by ryanblenis** [comment]
I've had the same and am currently investigating. I've narrow it down to changes implemented in MeshCentral 0.5.1-o, so I've reverted back to 0.5.1-n and working fine right now on my live instance.

Currently looking through the projects changes to see if it is MeshCentral related, or something that only affects this plugin. But others have [said the same](https://github.com/Ylianst/MeshCentral/issues/1149) about RDP in the main project, so I'm imagining it is affecting all MeshCentral users.

Just FYI, you can `npm i meshcentral@0.5.1-n` to get back to the previous version and get everyone up and running until the issue with the update breaking things is sorted out.

**Comment by ryanblenis** [comment]
Note that Ylian has reverted some changes and published 0.5.1-r which restores the functionality (which appears to have been breaking TCP/UDP tunnels for all implementations), so you can now just upgrade to the latest for that fix.
