### ISSUE TITLE
Possible to set multiple Work PCs?

### ISSUE THREAD

**Issue by jonopryor** [ryanblenis/MeshCentral-WorkFromHome#4]
Hi Ryan,

Love this plugin and it is proving very useful for us.

Would love to be able to set multiple Work PCs, and possibly have the RDP shortcut named as the PC name rather than Work_Computer.

Have looked through the code, but I don't know where to start with modifying it to do that.

**Comment by ryanblenis** [comment]
Hi @jonopryor,

Thanks for the request and kind words. Glad it is helping you. You'll find this new functionality in version 0.1.0 that was just released. Enjoy!

**Comment by jonopryor** [comment]
Absolute legend!
